config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  devise_for :users
  root 'home#top'
  resources :books
  resources :users
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  get 'relationships/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	 belongs_to :user
	 validates :title, presence: true
	 validates :body, presence: true, length: { maximum: 200 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # ユーザーをフォローする
    def follow(user_id)
        follower.create(followed_id: user_id)
    end

  # ユーザーのフォローを外す
    def unfollow(user_id)
        follower.find_by(followed_id: user_id).destroy
    end

  # フォローしていればtrueを返す
    def following?(user)
        following_user.include?(user)
    end

  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      # before_action :authenticate_user!
      before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
      user_path(current_user.id)
  end
  def after_sign_up_path_for(resource)
      user_path(current_user.id)
  end
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!

   def new
    @book = Book.new
   end

   def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
   end

   def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
       redirect_to books_path
    end
   end

   def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
    render "edit"
    end
   end

   def show
    @book = Book.new
    @user = User.find(current_user.id)
    @show_book = Book.find(params[:id])
   end

   def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "successfully"
       redirect_to books_path
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
   end

   private
   def book_params
       params.require(:book).permit(:title, :body)
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def show
    	@users = User.all
    	@user = User.find(current_user.id)
    end

	def follow
        current_user.follow(params[:id])
        redirect_to request.referer
    end

    def unfollow
        current_user.unfollow(params[:id])
        redirect_to request.referer
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  	@books = current_user.books
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "successfully"
       redirect_to user_path(current_user.id)
    else
       render :edit
    end
  end

  def destroy
  end

private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="col-md-6 col-md-offset-3">

<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <p>error</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= form_for(@book) do |f| %>

  <h4>Title</h4>
  <div class="field row">
    <%= f.text_field :title,class:"col-xs-12" %>
  </div>

  <h4>Opinion</h4>
  <div class="field row">
    <%= f.text_area :body, class:"col-xs-12" %>
  </div>

  <div class="field row">
    <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
  </div>

<% end %>
<%= link_to"Show", book_path(@book) %>
<%= link_to"Back", books_path %>

</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">


<div class="col-xs-3">
<h2>User info</h2>
 <table class="table">
  <tbody>
    <tr>
      <th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60' %></th>
    </tr>
    <tr>
     <th>name</th><th><%= @user.name %></th>
    </tr>
    <tr>
     <th>introduction</th><th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>フォロー数：<%= link_to "#{@user.follower.count}",relationships_show_path %></th>
    </tr>
    <tr>
      <th>フォロワー数：<%= link_to "#{@user.followed.count}",relationships_show_path %></th>
    </tr>
 </tbody>
</table>

<%= link_to"",edit_user_path(@user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h2>New book</h2>
  <%= form_for(@book) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class:"btn btn-primary" %>
<% end %>
</div>



<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <p>error</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="col-xs-9">
<h2>Books</h2>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

<% @books.each do |book| %>
<tbody>
  <tr>
    <%= link_to(book.user) do %>
      <td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60'%></td>
    <% end %>
      <td><%= link_to "#{book.title}", book_path(book) %></td>
      <td><%= book.body %></td>
  </tr>
</tbody>
<% end %>
</table>
</div>

</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">


<div class="col-xs-3">
<h2>User info</h2>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
 <table class="table">
  <tbody>
    <tr>
     <th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60'
%></th>
    </tr>
    <tr>
     <th>name</th><th><%= @user.name %></th>
    </tr>
    <tr>
     <th>introduction</th><th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>フォロー数：<%= link_to "#{@user.follower.count}",relationships_show_path %></th>
    </tr>
    <tr>
      <th>フォロワー数：<%= link_to "#{@user.followed.count}",relationships_show_path %></th>
    </tr>
  </tbody>
 </table>

<%= link_to"",edit_user_path(@user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h2>New book</h2>
  <%= form_for(@book) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class:"btn btn-primary" %>
<% end %>
</div>


<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

<tbody>
  <tr>
   <th><%= link_to(@show_book.user) do %>
    <%= attachment_image_tag @show_book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60'%>
    <%= @show_book.user.name %>
    <% end %>
   </th>

  <th><%= link_to "#{@show_book.title}", book_path(@show_book) %></th>
  <th><%= @show_book.body %></th>
     <% if current_user.id == @show_book.user_id %>
  <th><%= link_to "Edit", edit_book_path(@show_book) %></th>
  <th><%= link_to "Destroy", book_path(@show_book), method: :delete %></th>
     <% end %>
  </tr>
</tbody>

</table>

</div>
</div>
</div>

app/views/home/about.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">

   <h1>Welcome to<span class="glyphicon glyphicon-book">Bookers !!</h1>
</span>

</div>
</div>
</div>

app/views/home/top.html.erb
<div class="body">
<div class="container">
<p id="notice"></p>
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-3 col-md-6">

       <h1>Welcome to<span class="glyphicon glyphicon-book">Bookers !!</span></h1>

       <p>In<span><span class="glyphicon glyphicon-book"></span>Bookers,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p></span>

<div class="btn-wrapper">
  <div class="row">
    <%= link_to "Log In",new_user_session_path,class:"glyphicon glyphicon-log-in btn btn-info col-xs-10 col-xs-offset-1" %>
  </div>
  <div class="row">
    <%= link_to "Sign Up",new_user_registration_path,class:"glyphicon glyphicon-edit btn btn-success col-xs-10 col-xs-offset-1" %>
  </div>
</div>

</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
   <nav class="nav navbar-nav navbar-left">
     <h3>Bookers</h3></nav>
      <nav>
       <ul class="nav navbar-nav navbar-right">
     <% if user_signed_in? %>
         <li><%= link_to "Home",user_path(current_user),class:"glyphicon glyphicon-home home" %></li>

         <li><%= link_to "Users",users_path,class:"glyphicon glyphicon-user user" %></li>

         <li><%= link_to "Books",books_path,class:"glyphicon glyphicon-book book" %></li>

         <li><%= link_to "logout",destroy_user_session_path,method: :delete,class:"glyphicon glyphicon-log-in" %></li>

     <% else %>
         <li><%= link_to "Home",root_path,class:"glyphicon glyphicon-home home" %></li>

         <li><%= link_to "About",home_about_path,class:"glyphicon glyphicon-link about" %></li>

         <li><%= link_to "Sign up",new_user_registration_path,class:"glyphicon glyphicon-edit sign-up" %></li>

         <li><%= link_to " Login",new_user_session_path,class:"glyphicon glyphicon-log-in sign-in" %></li>
     <% end %>
      </ul>
     </nav>
 </div>
</header>


<p class="notice"><%= notice %></p>

<%= yield %>
</body>
</html>

app/views/relationships/show.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">


<div class="col-xs-9">
<h2>Follow Users</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>

<tbody>
<% @users.each do |user| %>
  <tr>
   <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60' %></th>
   <th><%= user.name %></th>
   <th><%= "フォロー数: #{@user.follower.count}" %></th>
   <th><%= "フォロワー数: #{@user.followed.count}" %></th>

   <% if user_signed_in? %>
     <th>
       <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
       <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
       <% end %>
     </th>
   <% end %>
   <th><%= link_to "Show", user_path(user) %></th>
  </tr>
<% end %>
</tbody>

</table>
</div>


</div>
</div>
</div>

app/views/users/edit.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">

<h2>User info</h2>
<%= form_for(@user) do |f| %>
<h4>Name</h4>
  <%= f.text_field :name %>
<h4>Profile image</h4>
  <%= f.attachment_field :profile_image %>
<h4>Introduction</h4>
  <%= f.text_area :introduction %><br>
  <%= f.submit 'Update User' %>
<% end %>

<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <p>error</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">


<div class="col-xs-3">
<h2>User info</h2>

 <table class="table">
  <tbody>
    <tr>
      <th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60' %></th>
    </tr>
    <tr>
     <th>name</th><th><%= @user.name %></th>
    </tr>
    <tr>
     <th>introduction</th><th><%= @user.introduction %></th>
    </tr>
  </tbody>
 </table>

<%= link_to"",edit_user_path(@user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h2>New book</h2>
  <%= form_for(@book) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class:"btn btn-primary" %>
<% end %>
</div>


<div class="col-xs-9">
<h2>Users</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>

<tbody>
<% @users.each do |user| %>
  <tr>
   <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60' %></th>
   <th><%= user.name %></th>
   <th><%= link_to "Show", user_path(user) %></th>
  </tr>
<% end %>
</tbody>

</table>
</div>

</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row" style="margin-top: 55px">
<div class="top-message col-md-offset-0 col-md-10">


<div class="col-xs-3">
<h2>User info</h2>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
 <table class="table">
  <tbody>
    <tr>
       <th><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60'
%></th>
    </tr>
    <tr>
       <th>name</th><th><%= @user.name %></th>
    </tr>
    <tr>
       <th>introduction</th><th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>フォロー数：<%= link_to "#{@user.follower.count}",relationships_show_path %></th>
    </tr>
    <tr>
      <th>フォロワー数：<%= link_to "#{@user.followed.count}",relationships_show_path %></th>
    </tr>

    <tr>
     <% if user_signed_in? %>
      <th>
      <% if current_user.following?(@user) %>
          <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
      <% else %>
          <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
      <% end %>
      </th>
     <% end %>
    </tr>

  </tbody>
 </table>

<%= link_to"",edit_user_path(@user.id),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h2>New book</h2>
  <%= form_for(@book) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class:"btn btn-primary" %>
<% end %>
</div>

<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

<% @books.each do |book| %>
<tbody>
  <tr>
    <td><%= link_to(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60'%>
        <% end %>
    </td>
    <td><%= link_to "#{book.title}", book_path(book) %></td>
    <td><%= book.body %></td>
  </tr>
</tbody>
<% end %>
</table>
</div>

</div>
</div>
</div>